### ISSUE TITLE
Lower than expected results

### ISSUE THREAD

**Issue by pjordab** [privefl/paper-ldpred2#6]
Dear Florian, 

Our group is using LDpred2 for the development of polygenic scores. After obtaining lower than expected results, we have tried to simulate the results of the paper with the summary statitics of Nipkay et al. for CAD. 

The paper describes an AUC for LDpred2 auto genome-wide of 61.8 [61.3-62.3]. 

In our case, we obtain 0.54 [0.53-0.55].

We have checked the summary statistics, genotypes and phenotypes and the information is correct. We have also checked the code thoroughly but did not detect the bug. Would it be possible to share the code we have used with you? If you have any other suggestions on how we can review your input data or results, we would also really appreciate it. 

Thank you very much in advance!

Paloma

**Comment by privefl** [comment]
Sorry, but I don't have time to look thoroughly at your code.

Quick feedback:

- the defintion of phenotypes: https://github.com/privefl/paper-ldpred2/blob/master/code/prepare-phenotypes.R
- if the positions are really a problem, you can also match using rsids instead of positions
- the initial value for h2 in LDpred2-auto (that you get from ldsc) should have very little to no impact on the results
- N=15K; are you using other sumstats or is it the sample size in your test set?

**Comment by privefl** [comment]
Could you try to use the LD ref provided after matching with the variants you have?
